connect:
  #build: connect
  image: anvilresearch/connect:<%= version %>
  links:
    - redis
  volumes:
    - ./connect/config:/opt/connect/config:ro
    - ./connect/email:/opt/connect/email:ro
    - ./connect/protocols:/opt/connect/protocols:ro
    - ./connect/providers:/opt/connect/providers:ro
    - ./connect/public:/opt/connect/public:ro
    - ./connect/views:/opt/connect/views:ro
  restart: always

nginx:
  #build: nginx
  image: anvilresearch/nginx
  links:
    - connect
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/certs:/etc/nginx/certs:ro
    - ./nginx/logs:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"
  restart: always

redis:
  #build: redis
  image: anvilresearch/redis
  volumes:
    - ./redis/data:/data
  restart: always
